# .pre-commit-config.yaml

# Other usable hooks https://pre-commit.com/hooks.html

default_language_version:
  python: python3.12

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        args: []

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)

  # - repo: local
  #   hooks:
  #     - id: docker-compose-check
  #       exclude: '(^|/)(frontend|hooks|.github)/'
  #       name: Docker Compose up check
  #       entry: docker-compose
  #       args: ['up', '--build', '.', '--exit-code-from', 'backend']
  #       language: system
